/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_simulation_free: (a: number, b: number) => void;
export const simulation_add_particles: (a: number, b: number, c: number, d: number) => number;
export const simulation_get_count: (a: number) => number;
export const simulation_get_materials: (a: number) => [number, number];
export const simulation_get_phases: (a: number) => [number, number];
export const simulation_get_positions: (a: number) => [number, number];
export const simulation_get_sleep_count: (a: number) => number;
export const simulation_get_spray_count: (a: number) => number;
export const simulation_get_spray_materials: (a: number) => [number, number];
export const simulation_get_spray_positions: (a: number) => [number, number];
export const simulation_get_temperatures: (a: number) => [number, number];
export const simulation_get_velocities: (a: number) => [number, number];
export const simulation_new: () => number;
export const simulation_reset: (a: number) => void;
export const simulation_set_bounds: (a: number, b: number, c: number, d: number) => void;
export const simulation_step: (a: number, b: number, c: number, d: number) => void;
export const __wbg_mpmsimulation_free: (a: number, b: number) => void;
export const mpmsimulation_add_particles: (a: number, b: number, c: number, d: number) => number;
export const mpmsimulation_get_count: (a: number) => number;
export const mpmsimulation_get_mat_ids: (a: number) => [number, number];
export const mpmsimulation_get_positions: (a: number) => [number, number];
export const mpmsimulation_get_velocities: (a: number) => [number, number];
export const mpmsimulation_new: () => number;
export const mpmsimulation_reset: (a: number) => void;
export const mpmsimulation_set_bounds: (a: number, b: number, c: number, d: number) => void;
export const mpmsimulation_step: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
