// Classifier parity test for the worker office.
//
//   node scripts/classify-test.mjs
//
// 1. office/observer/classify.mjs must reproduce EVERY output of the Python reference recorded in the shared fixture
//    office/observer/classify-cases.json (generated by scripts/gen-classify-cases.py): the final self-test, the 48
//    step-3 cases, the self-test asserts, every tool-name branch, batches, the hook-time Agent rule and parser edge
//    cases, including the steps() split and the heredoc-stripped text of every shell case.
// 2. Planted wrong rules MUST FAIL the same suite. Each mutant is a one-line textual change of a copy of classify.mjs
//    (the target line must exist exactly once), imported from a temp folder. The first mutant is the one the plan
//    names: the step-3 first-segment rule instead of precedence.
// 3. Module-level invariants the hook relies on (closed sets for kinds and activity ids, hook-time rules).
// In-process only: no child processes, no network, nothing written outside one temp folder that is removed.
import { readFileSync, writeFileSync, mkdtempSync, unlinkSync, rmdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { isDeepStrictEqual } from 'node:util';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CLASSIFY = join(ROOT, 'office', 'observer', 'classify.mjs');
const FIXTURE = JSON.parse(readFileSync(join(ROOT, 'office', 'observer', 'classify-cases.json'), 'utf8'));

const plain = (x) => (Array.isArray(x) ? x.map(plain) : x);

/** Runs every fixture case against module m. Returns {n, fails: [{section, label, got, want}]}. */
export function runSuite(m, fx = FIXTURE) {
  const fails = [];
  let n = 0;
  const check = (section, label, got, want) => {
    n += 1;
    let g;
    try { g = plain(got()); } catch (e) { g = `THREW ${e && e.name}: ${e && e.message}`; }
    if (!isDeepStrictEqual(g, want)) fails.push({ section, label, got: g, want });
  };
  const call = (fn, args) => {
    if (fn === 'classifyShell') return m.classifyShell(...args);
    if (fn === 'classifyBatch') return m.classifyBatch(...args);
    if (fn === 'classifyAgentPre') return m.classifyAgentPre(...args);
    if (fn === 'classify') return m.classify(...args);
    throw new Error(`unknown fn ${fn}`);
  };
  for (const section of ['shell', 'shellStep3', 'edge']) {
    for (const c of fx[section]) {
      const label = JSON.stringify(c.cmd);
      check(section, label, () => m.classifyShell(c.cmd), c.py);
      if ('expectKind' in c) check(section + ':expectKind', label, () => m.classifyShell(c.cmd)[1], c.expectKind);
      check(section + ':steps', label, () => m.steps(c.cmd), c.pySteps);
      check(section + ':stripHeredocs', label, () => m.stripHeredocs(c.cmd), c.pyStripped);
    }
  }
  for (const section of ['asserts', 'step3Asserts']) {
    for (const a of fx[section]) {
      const label = `${a.fn}(${JSON.stringify(a.args)})`;
      check(section, label, () => call(a.fn, a.args), a.py);
      check(section + ':field', label, () => call(a.fn, a.args)[a.field], a.expect);
    }
  }
  for (const c of fx.firstSegment) {
    const label = JSON.stringify(c.cmd);
    check('firstSegment:rule', label, () => m.classifyShellFirstSegment(c.cmd), c.pyFirstSegment);
    check('firstSegment:differs', label, () => m.classifyShellFirstSegment(c.cmd)[1] !== c.expectKind, true);
    check('firstSegment:precedence', label, () => m.classifyShell(c.cmd)[1], c.expectKind);
  }
  for (const c of fx.tools) check('tools', JSON.stringify(c.args), () => m.classify(...c.args), c.py);
  for (const c of fx.batch) check('batch', JSON.stringify(c.args), () => m.classifyBatch(...c.args), c.py);
  for (const c of fx.agentPre) check('agentPre', JSON.stringify(c.args), () => m.classifyAgentPre(...c.args), c.py);
  return { n, fails };
}

/** Invariants of the real module that the hook and the observer rely on. Returns a list of failure strings. */
function invariants(m, fx = FIXTURE) {
  const bad = [];
  const expect = (cond, what) => { if (!cond) bad.push(what); };
  // closed sets
  expect(m.PRECEDENCE.length === 17 && new Set(m.PRECEDENCE).size === 17, 'PRECEDENCE has 17 distinct kinds');
  const ids = [...m.ACTIVITY_ID.values()];
  expect(m.ACTIVITY_ID.size === 35 && new Set(ids).size === ids.length, 'activity ids are 1:1 (35 activities)');
  expect(ids.every((id) => /^[a-z][a-z-]{1,15}$/.test(id)), 'activity ids are short lowercase slugs');
  expect([...m.ACTIVITY_BY_ID].every(([id, a]) => m.ACTIVITY_ID.get(a) === id), 'ACTIVITY_BY_ID inverts ACTIVITY_ID');
  const outputs = [];
  for (const s of ['shell', 'shellStep3', 'edge']) for (const c of fx[s]) outputs.push(c.py);
  for (const s of ['asserts', 'step3Asserts', 'tools', 'batch', 'agentPre']) for (const c of fx[s]) outputs.push(c.py);
  const acts = new Set(outputs.map((o) => o[0]));
  for (const a of acts) expect(m.ACTIVITY_ID.has(a), `activity has an id: ${a}`);
  for (const o of outputs) expect(o[1] === null || m.KINDS.has(o[1]), `kind in the closed set: ${o[1]}`);
  expect(acts.size >= 30, `fixture exercises at least 30 of the 35 activities (got ${acts.size})`);
  // hook-time rules
  const eq = (got, want, what) => expect(isDeepStrictEqual(plain(got), want), `${what}: got ${JSON.stringify(plain(got))}`);
  eq(m.classifyCallAtHook('Agent', {}), ['launch own background helper', 'frontDesk'], 'hook Agent, flag omitted');
  eq(m.classifyCallAtHook('Agent', { run_in_background: false }), ['call own foreground helper', 'meetingTable'], 'hook Agent, explicit false');
  eq(m.classifyCallAtHook('Agent', {}, 'completed'), ['call own foreground helper', 'meetingTable'], 'hook Agent, status completed');
  eq(m.classifyCallAtHook('Agent', { run_in_background: false }, 'async_launched'), ['launch own background helper', 'frontDesk'], 'hook Agent, status async_launched');
  eq(m.classifyCallAtHook('Agent', { run_in_background: false }, 'weird'), ['call own foreground helper', 'meetingTable'], 'hook Agent, unknown status falls back');
  eq(m.classifyCallAtHook('ToolSearch', { query: 'x' }), ['look up a tool', null], 'hook ToolSearch is deferred');
  eq(m.classify('ToolSearch', null, 'bookshelf'), ['look up a tool', 'manualsShelf'], 'observer resolves ToolSearch in the library');
  for (const c of fx.tools) {
    const [name, inp, cur, res] = c.args;
    if (name === 'Agent' || name === 'ToolSearch' || cur !== null || res !== '') continue;
    eq(m.classifyCallAtHook(name, inp), c.py, `hook rule = reference for ${name}`);
  }
  eq(m.classifyBatchAtHook([['ToolSearch', {}, null], ['Read', {}, null]]), ['read a file', 'fileCabinet'], 'hook batch: ToolSearch + Read');
  eq(m.classifyBatchAtHook([['Agent', {}, null], ['Bash', { command: 'npm test' }, null]]), ['launch own background helper', 'frontDesk'], 'hook batch: Agent default + run');
  eq(m.classifyBatchAtHook([['Edit', {}, null], ['Agent', {}, 'completed']]), ['call own foreground helper', 'meetingTable'], 'hook batch: fg Agent + Edit');
  eq(m.classifyBatchAtHook([['Bash', { command: 'git status' }, null], ['Bash', { command: 'git diff' }, null]]), ['compare versions', 'lectern'], 'hook batch: precedence');
  eq(m.classifyBatchAtHook([]), ['no move', null], 'hook batch: empty');
  // where the reference raises, the port raises (the hook then writes its record without a kind)
  const throws = (f) => { try { f(); return false; } catch (e) { return e instanceof TypeError; } };
  expect(throws(() => m.classify('Bash', 'not a dict')), 'Bash with a non-dict tool_input raises (Python: AttributeError)');
  expect(throws(() => m.classify('Bash', { command: 5 })), 'Bash with a non-string command raises');
  expect(throws(() => m.classifyAgentPre(['x'])), 'Agent with a list tool_input raises');
  eq(m.classify('Read', 'not a dict'), ['read a file', 'fileCabinet'], 'Read ignores its input (Python does not read it either)');
  eq(m.classify('Bash', { command: [] }), ['no move', null], 'empty list command is falsy, like Python');
  eq(m.classify('Bash', { constructor: 'x' }), ['no move', null], 'no prototype keys are read');
  eq(m.classifyShell('constructor x && __proto__ y'), ['no move', null], 'no prototype verbs');
  return bad;
}

// Mutants: [name, what it plants, [[exact target text, replacement], ...]]. Each target must occur exactly once.
// Rule mutants switch off one rule of the plan; compat mutants swap one Python-compatibility detail for the
// JS-native behaviour (the port would look right on plain ASCII input and still be wrong).
const MUTANTS = [
  ['shell-first-segment', 'P1 off: the step-3 first-segment rule instead of precedence (the plan\'s planted wrong rule)',
    [['return classifyShellPrec(cmd, depth);   // [mutation-target:shell-raw]', 'return classifyShellFirstSegment(cmd, depth);']]],
  ['batch-newest-wins', 'a parallel batch takes its newest call instead of precedence',
    [['if (best === null || rank(r[1]) < rank(best[1])) best = r;   // [mutation-target:batch]', 'best = r;']]],
  ['git-relabels-off', 'P2 off: checkout/stash/status keep their step-3 labels',
    [['applyGitRelabels(GIT);   // [mutation-target:git-relabel]', '']]],
  ['agent-omitted-is-foreground', 'P3 off: an omitted run_in_background means foreground (the step-3 default)',
    [["const explicitFalse = rib === false || (typeof rib === 'string' && rib.toLowerCase() === 'false');   // [mutation-target:agent-pre]",
      "const explicitFalse = !(rib === true || (typeof rib === 'string' && rib.toLowerCase() === 'true'));"]]],
  ['heredoc-bodies-kept', 'heredoc / here-string bodies are classified as commands',
    [['const text = stripHeredocs(cmd);   // [mutation-target:heredoc]', "const text = pyOr(cmd, '');"]]],
  ['pipe-stages-ranked', 'every pipeline stage ranks on its own (no producer rule)',
    [["if (c === '|') { endStage(); i += 1; continue; }   // [mutation-target:pipe]", "if (c === '|') { endStep(); i += 1; continue; }"]]],
  ['compat-js-whitespace-class', 'regexes use JS \\s instead of Python\'s whitespace set',
    [["const PY_WS = '\\\\t\\\\n\\\\v\\\\f\\\\r\\\\x1c-\\\\x1f \\\\x85\\\\xa0\\\\u1680\\\\u2000-\\\\u200a\\\\u2028\\\\u2029\\\\u202f\\\\u205f\\\\u3000';",
      "const PY_WS = '\\\\s';"]]],
  ['compat-js-trim', 'strip() is JS trim() (drops the BOM, keeps \\x1c-\\x1f and \\x85)',
    [['function pyStrip(s) {', 'function pyStrip(s) { return s.trim();'],
     ['function pyLstrip(s) {', 'function pyLstrip(s) { return s.trimStart();']]],
  ['compat-js-dot', "Python '.' (anything but \\n) written as JS '.' (also refuses \\r, \\u2028, \\u2029)",
    [["|[A-Za-z]:[\\\\/][^\\n]*|\\/[^\\n]*)$/;", '|[A-Za-z]:[\\\\/].*|\\/.*)$/;'],
     ['/^([\"\'][^\\n]*|', '/^([\"\'].*|'],
     ['\\+?=([^\\n]*)$/;', '\\+?=(.*)$/;']]],
  ['compat-js-icase', "(?i) 'in background' without Python's dotless-i / dotted-I equivalence",
    [['const RE_AGENT_BG_TEXT = /launched|[i\\u0131\\u0130]n background/iu;', 'const RE_AGENT_BG_TEXT = /launched|in background/iu;']]],
  ['compat-js-or', "Python 'x or y' written as JS 'x || y' (empty list / dict are truthy in JS)",
    [['function pyOr(a, b) { return pyTruthy(a) ? a : b; }', 'function pyOr(a, b) { return a || b; }']]],
  ['compat-js-digit', 'Python \\d (Unicode Nd) written as JS \\d (ASCII only)',
    [['const RE_PY3 = /^python3(\\.\\p{Nd}+)?$/u;', 'const RE_PY3 = /^python3(\\.\\d+)?$/u;'],
     ['const RE_DUP_REDIRECT = /\\p{Nd}?>&\\p{Nd}/gu;', 'const RE_DUP_REDIRECT = /\\d?>&\\d/gu;'],
     ['`\\\\p{Nd}>>?[${PY_WS}]*', '`\\\\d>>?[${PY_WS}]*']]],
  ['compat-js-word', 'Python \\w (Unicode letters and digits) written as JS \\w (ASCII only)',
    [['const RE_FUNC_HEADER = /^[A-Za-z_][\\p{L}\\p{N}_-]*\\(\\)$/u;', 'const RE_FUNC_HEADER = /^[A-Za-z_][\\w-]*\\(\\)$/u;']]],
];

async function main() {
  let failed = false;
  const real = await import(pathToFileURL(CLASSIFY).href);
  const r = runSuite(real);
  console.log(`classifier vs Python reference: ${r.n - r.fails.length}/${r.n} checks pass`);
  for (const f of r.fails.slice(0, 25)) console.log('  FAIL', f.section, f.label, '\n     got ', JSON.stringify(f.got), '\n     want', JSON.stringify(f.want));
  if (r.fails.length) failed = true;
  const counts = Object.fromEntries(['shell', 'shellStep3', 'asserts', 'step3Asserts', 'firstSegment', 'tools', 'batch', 'agentPre', 'edge'].map((k) => [k, FIXTURE[k].length]));
  console.log('  fixture cases:', JSON.stringify(counts), 'reference sha256:', FIXTURE.reference['classify_final.py'].slice(0, 12));

  const inv = invariants(real);
  console.log(`module invariants: ${inv.length ? inv.length + ' FAIL' : 'PASS'}`);
  for (const b of inv) console.log('  FAIL', b);
  if (inv.length) failed = true;

  const src = readFileSync(CLASSIFY, 'utf8');
  const dir = mkdtempSync(join(tmpdir(), 'wo-classify-mutants-'));
  const written = [];
  try {
    for (const [name, what, edits] of MUTANTS) {
      let mutated = src, ok = true;
      for (const [target, replacement] of edits) {
        const hits = mutated.split(target).length - 1;
        if (hits !== 1) { console.log(`MUTANT ${name}: target found ${hits} times (must be exactly 1): ${target}`); ok = false; break; }
        mutated = mutated.replace(target, () => replacement);
      }
      if (!ok) { failed = true; continue; }
      const file = join(dir, `classify.${name}.mjs`);
      writeFileSync(file, mutated);
      written.push(file);
      const mod = await import(pathToFileURL(file).href);
      const mr = runSuite(mod);
      const sections = [...new Set(mr.fails.map((f) => f.section))];
      const caught = mr.fails.length > 0;
      console.log(`MUTANT ${name}: ${caught ? 'CAUGHT' : 'NOT CAUGHT'} (${mr.fails.length} of ${mr.n} checks fail; ${sections.join(', ')}) -- ${what}`);
      if (name === 'shell-first-segment') {
        const p1 = FIXTURE.firstSegment.map((c) => JSON.stringify(c.cmd));
        const missed = p1.filter((l) => !mr.fails.some((f) => f.section === 'shell' && f.label === l));
        if (missed.length) { console.log('  the first-segment mutant did not fail these P1 cases:', missed.join(' ')); failed = true; }
      }
      if (!caught) failed = true;
    }
  } finally {
    for (const f of written) { try { unlinkSync(f); } catch { /* ignore */ } }
    try { rmdirSync(dir); } catch { /* ignore */ }
  }
  console.log(failed ? 'CLASSIFIER TEST: FAIL' : 'CLASSIFIER TEST: PASS');
  process.exitCode = failed ? 1 : 0;
}

const isMain = process.argv[1] && resolve(process.argv[1]).toLowerCase() === fileURLToPath(import.meta.url).toLowerCase();
if (isMain) await main();
