# Generates office/observer/classify-cases.json, the ONE shared fixture for the worker-office classifier
# (office/observer/classify.mjs). Every expected value in the fixture is the OUTPUT OF THE PYTHON REFERENCE
# (classify_final.py, which imports classify_s3.py), run here; nothing is typed by hand except the inputs.
#
#   python scripts/gen-classify-cases.py [path/to/classify_final.py]
#
# Default reference path = the planning scratchpad of session 944994c0 (see the worker-office plan, Appendix B).
# The fixture records the sha256 of both reference files, the Python and Unicode-database versions, and is
# byte-for-byte deterministic (no timestamps), so a re-run against the same reference reproduces it exactly.
#
# Sections
#   shell        classify_final.TESTS (the self-test's 41 cases; expectKind = the self-test's own answer)
#   shellStep3   classify_s3.TESTS run through the FINAL classifier (plan 4.3: "the 48 step-3 cases all still pass")
#   asserts      the self-test's 7 asserts, one case each
#   step3Asserts classify_s3's Agent asserts and machine-check cases, run through the final classifier
#   firstSegment the self-test's mutation check: the step-3 first-segment rule must give a DIFFERENT kind
#   tools        every tool-name branch of classify() (reference outputs)
#   batch        classify_batch cases (reference outputs)
#   agentPre     classify_agent_pre cases (reference outputs)
#   edge         hand-picked parser edge cases (quotes, heredocs, here-strings, Unicode whitespace, R2 nesting...)
#   nest         P4, the segment-nesting bound: chains at, below and above MAX_SEGMENT_NEST, stored as a recipe
#                (cmd = pre * k + mid + post * k) so long chains stay small here; the port rebuilds the same string
#   batchStations every batch (and every one-call batch) at every station kind: the reference classify_batch with
#                cur_kind = that station (the oracle for the observer's station rule, classify.mjs resolveAtStation)
#   unicode      Python's own \d and \w as code-point ranges, read by running re over every code point 0..0x10FFFF
#                (the port embeds these exact tables instead of trusting the JS engine's Unicode version)
# Every shell case also carries the reference steps() split and the heredoc-stripped text, so a port
# mismatch can be located in the splitter or in the segment classifier.
import hashlib, json, os, pathlib, platform, re, sys, unicodedata, importlib.util

HERE = pathlib.Path(__file__).resolve().parent
DEFAULT_REF = pathlib.Path(r'C:/Users/ddogr/AppData/Local/Temp/claude/C--Users-ddogr-OneDrive-Desktop-Questions/'
                           r'944994c0-d7e9-4be1-a2a7-032471f945b2/scratchpad/office/plan/classify_final.py')
REF = pathlib.Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else DEFAULT_REF
OUT = HERE.parent / 'office' / 'observer' / 'classify-cases.json'

for k in ('CF_GIT_RELABEL', 'CF_SHELL_PREC', 'CF_BATCH_PREC'):       # the reference's decomposition toggles
    assert os.environ.get(k, '1') != '0', f'{k}=0 would generate a fixture for a classifier that does not ship'

spec = importlib.util.spec_from_file_location('classify_final', REF)
cf = importlib.util.module_from_spec(spec); spec.loader.exec_module(cf)
c3 = cf.c3

def sha(p): return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def out(r): return [r[0], r[1]]
def shell_case(cmd, **extra):
    d = {'cmd': cmd, 'py': out(cf.classify_shell(cmd)), 'pySteps': cf.steps(cmd), 'pyStripped': cf._strip_heredocs(cmd)}
    d.update(extra); return d

fx = {
    'about': 'Shared fixture for office/observer/classify.mjs. Every "py" value is the output of the Python '
             'reference classify_final.py (plan 4.3), generated by scripts/gen-classify-cases.py. Do not edit by hand.',
    'generator': 'scripts/gen-classify-cases.py',
    'reference': {'classify_final.py': sha(REF), 'classify_s3.py': sha(cf._P)},
    'python': platform.python_version(), 'unicodedata': unicodedata.unidata_version,
    'maxSegmentNest': cf.MAX_SEGMENT_NEST,
}

# ---- shell: the final self-test
fx['shell'] = [shell_case(c, expectKind=e) for c, e in cf.TESTS]
bad = [d['cmd'] for d in fx['shell'] if d['py'][1] != d['expectKind']]
assert not bad, ('reference fails its own self-test', bad)

# ---- shellStep3: the step-3 cases under the final classifier
fx['shellStep3'] = [shell_case(c, expectKind=e) for c, e in c3.TESTS]
bad3 = [d['cmd'] for d in fx['shellStep3'] if d['py'][1] != d['expectKind']]
assert not bad3, ('a step-3 case changed under the final classifier', bad3)

# ---- asserts: the final self-test's 7 asserts
A = []
A.append({'fn': 'classifyShell', 'args': ['git status'], 'field': 0, 'expect': 'glance at history'})
A.append({'fn': 'classifyShell', 'args': ['git checkout main'], 'field': 0, 'expect': 'restore files'})
A.append({'fn': 'classifyBatch', 'args': [[['Read', {}, 'a'], ['Bash', {'command': 'npm test'}, 'b']]], 'field': 1, 'expect': 'benchTerminal'})
A.append({'fn': 'classifyBatch', 'args': [[['Grep', {}, 'a'], ['Bash', {'command': 'git log -3'}, 'b']]], 'field': 1, 'expect': 'historyShelf'})
A.append({'fn': 'classifyBatch', 'args': [[['Bash', {'command': 'cd x'}, 'a']]], 'field': 1, 'expect': None})
A.append({'fn': 'classifyAgentPre', 'args': [{}], 'field': 1, 'expect': 'frontDesk'})
A.append({'fn': 'classifyAgentPre', 'args': [{'run_in_background': True}], 'field': 1, 'expect': 'frontDesk'})
A.append({'fn': 'classifyAgentPre', 'args': [{'run_in_background': False}], 'field': 1, 'expect': 'meetingTable'})
def call(fn, args):
    if fn == 'classifyShell': return cf.classify_shell(*args)
    if fn == 'classifyBatch': return cf.classify_batch([tuple(x) for x in args[0]], *args[1:])
    if fn == 'classifyAgentPre': return cf.classify_agent_pre(*args)
    if fn == 'classify': return cf.classify(*args)
    raise ValueError(fn)
for a in A:
    a['py'] = out(call(a['fn'], a['args']))
    assert a['py'][a['field']] == a['expect'], a
fx['asserts'] = A    # 8 entries: the self-test's 6th assert checks two inputs

# ---- step3Asserts: classify_s3's own Agent asserts + the machine-check list, through the final classifier
S = [{'fn': 'classify', 'args': ['Agent', {'run_in_background': 'true'}, None, ''], 'field': 1, 'expect': 'frontDesk'},
     {'fn': 'classify', 'args': ['Agent', {}, None, 'Fork started \u2014 processing in background'], 'field': 1, 'expect': 'frontDesk'},
     {'fn': 'classify', 'args': ['Agent', {}, None, ''], 'field': 1, 'expect': 'meetingTable'}]
MC = ['powershell -NoProfile -Command "Get-Process node"', 'nvidia-smi',
      '[math]::Round((Get-CimInstance Win32_OperatingSystem).FreePhysicalMemory/1MB, 2)',
      '"{0:N2} GB free" -f ((Get-CimInstance Win32_OperatingSystem).FreePhysicalMemory/1MB)',
      'try { (Get-CimInstance -Namespace root/wmi -ClassName BatteryStatus) | Select-Object PowerOnline } catch {}',
      '$free=(Get-CimInstance Win32_OperatingSystem).FreePhysicalMemory']
S += [{'fn': 'classifyShell', 'args': [c], 'field': 0, 'expect': 'check the machine'} for c in MC]
S += [{'fn': 'classifyShell', 'args': [c], 'field': 1, 'expect': 'benchTerminal'} for c in MC]
for a in S:
    a['py'] = out(call(a['fn'], a['args']))
    assert a['py'][a['field']] == a['expect'], a
fx['step3Asserts'] = S

# ---- firstSegment: the reference's own mutation check (the step-3 rule must FAIL the P1 cases)
P1 = ['ls dist && node scripts/a.mjs', 'git status && git diff --stat', 'curl -s https://x > a.json && python parse.py']
exp = {c: e for c, e in cf.TESTS}
fs = [{'cmd': c, 'expectKind': exp[c], 'pyFirstSegment': out(cf._first_segment_raw(c))} for c in P1]
assert all(d['pyFirstSegment'][1] != d['expectKind'] for d in fs), fs
fx['firstSegment'] = fs

# ---- tools: every tool-name branch of classify() (reference outputs)
T = []
def tool(name, inp, cur=None, res=''): T.append({'args': [name, inp, cur, res]})
tool('Bash', {'command': 'git log -3'}); tool('PowerShell', {'command': 'Get-Content a.txt'})
tool('Bash', {}); tool('Bash', None); tool('Bash', {'command': None}); tool('Bash', {'command': ''})
# Python truthiness: empty list / dict / 0 are falsy ("x or default"), unlike JS ||
tool('Bash', {'command': []}); tool('Bash', {'command': {}}); tool('Bash', {'command': 0}); tool('Bash', [])
tool('Agent', [], None, ''); tool('Agent', {}, None, 'ın background'); tool('Agent', {}, None, 'İn BACKGROUND')
for n in ('Read', 'NotebookRead', 'Grep', 'Glob', 'LSP', 'Edit', 'MultiEdit', 'Write', 'NotebookEdit', 'WebSearch',
          'WebFetch', 'ListMcpResourcesTool', 'ReadMcpResourceTool', 'Skill', 'TaskCreate', 'TodoWrite', 'CronCreate',
          'TaskUpdate', 'CronDelete', 'TaskList', 'TaskGet', 'CronList', 'Workflow', 'SendMessage', 'PushNotification',
          'SendUserFile', 'Monitor', 'TaskStop', 'ListAgents', 'SubagentHandback', 'StructuredOutput', 'AskUserQuestion',
          'Artifact', 'TaskOutput', 'EnterWorktree', 'Foo', ''):
    tool(n, {})
tool(None, {})
for cur in (None, 'bookshelf', 'readingLedge', 'cardCatalog', 'manualsShelf', 'readingTable', 'fileCabinet', 'pcDesk'):
    tool('ToolSearch', {'query': 'x'}, cur)
for inp, res in (({}, ''), ({'run_in_background': True}, ''), ({'run_in_background': 'true'}, ''),
                 ({'run_in_background': 'TRUE'}, ''), ({'run_in_background': False}, ''), ({'run_in_background': 'false'}, ''),
                 ({'run_in_background': 1}, ''), ({'run_in_background': None}, ''), ({}, 'async_launched'),
                 ({}, '{"status":"async_launched"}'), ({}, 'Agent LAUNCHED ok'), ({}, 'running In Background now'),
                 ({}, 'completed'), ({}, 'background'), (None, '')):
    tool('Agent', inp, None, res)
for n in ('mcp__plugin_chrome-devtools-mcp_chrome-devtools__click', 'mcp__claude-in-chrome__navigate',
          'mcp__plugin_playwright_playwright__browser_click', 'mcp__ide__getDiagnostics', 'mcp__blender__get_scene_info',
          'mcp__plugin_figma_figma__authenticate', 'mcp__Roblox_Studio__script_read', 'mcp__plugin_context7_context7__query-docs',
          'mcp__claude_ai_Google_Calendar__list_events', 'mcp__claude_ai_Notion__notion-create-pages',
          'mcp__claude_ai_Notion__notion-fetch', 'mcp__claude_ai_Google_Drive__copy_file',
          'mcp__claude_ai_Google_Drive__read_file_content', 'mcp__claude_ai_Gmail__send_message',
          'mcp__claude_ai_Gmail__get_thread', 'mcp__claude_ai_Gmail__create_draft', 'mcp__plugin_slack_slack__authenticate',
          'mcp__slack__post_message', 'mcp__telegram__reply', 'mcp__unknown_server__do_thing', 'mcp__', 'mcp__x',
          'mcp____y', 'MCP__chrome__x'):
    tool(n, {})
for t in T: t['py'] = out(cf.classify(*t['args']))
fx['tools'] = T

# ---- batch (reference outputs)
B = []
def batch(calls, cur=None, results=None): B.append({'args': [calls, cur, results]})
batch([['Read', {}, 'a'], ['Bash', {'command': 'npm test'}, 'b']])
batch([['Grep', {}, 'a'], ['Bash', {'command': 'git log -3'}, 'b']])
batch([['Bash', {'command': 'cd x'}, 'a']]); batch([])
batch([['Read', {}, 'a'], ['Grep', {}, 'b']]); batch([['Grep', {}, 'a'], ['Read', {}, 'b']])     # tie: first kept
batch([['Edit', {}, 'a'], ['Bash', {'command': 'rm -rf x'}, 'b']]); batch([['WebFetch', {}, 'a'], ['WebSearch', {}, 'b']])
batch([['ToolSearch', {}, 'a'], ['Read', {}, 'b']]); batch([['ToolSearch', {}, 'a'], ['Read', {}, 'b']], 'bookshelf')
batch([['Agent', {}, 'a'], ['Bash', {'command': 'npm test'}, 'b']])
batch([['Agent', {}, 'a'], ['Bash', {'command': 'npm test'}, 'b']], None, {'a': 'async_launched'})
batch([['Bash', {'command': 'cd x'}, 'a'], ['Foo', {}, 'b']]); batch([['Foo', {}, 'a'], ['Bash', {'command': 'ls'}, 'b']])
batch([['SubagentHandback', {}, 'a'], ['StructuredOutput', {}, 'b'], ['Bash', {'command': 'node a.js'}, 'c']])
for b in B:
    calls, cur, results = b['args']
    b['py'] = out(cf.classify_batch([tuple(x) for x in calls], cur, results))
fx['batch'] = B

# ---- agentPre (reference outputs)
P = [{'args': [x]} for x in ({}, None, {'run_in_background': True}, {'run_in_background': False},
                             {'run_in_background': 'false'}, {'run_in_background': 'FALSE'}, {'run_in_background': 'False'},
                             {'run_in_background': 'true'}, {'run_in_background': 0}, {'run_in_background': 1},
                             {'run_in_background': None}, {'run_in_background': [False]}, {'run_in_background': 'no'},
                             {'run_in_background': ' false'}, {'description': 'x'}, [], '', 0)]
for p in P: p['py'] = out(cf.classify_agent_pre(*p['args']))
fx['agentPre'] = P

# ---- edge: parser edge cases (reference outputs only)
E = [
    '', '   ', ';;', '&& ||', '|', 'cd a; cd b', 'echo a | grep b', 'foo | grep x', 'grep x | foo', 'cat a | python b.py',
    'ls -la\r', 'ls\r\ncat a', 'cat a\x0bnode b', 'cat\u00a0a.txt', 'cat\u3000a && node b', 'cat a\u2028node b',
    'ls\x1cnode', 'ls\x85node b', 'ls\ufeffnode b', 'echo "unbalanced && node a.js', "echo 'x | node a", 'echo "a" "b',
    'echo "x\\" && node a.js" && ls', "echo 'x\\' && node a.js", 'a="b;c" node x.js', 'a="b && c" && cat f',
    'cat <<EOF\nrm -rf /\nEOF\nnode a.js', 'cat <<-EOF > f\n\trm x\n\tEOF\nls', 'cat << "END" > f\nrm x\nEND',
    "cat <<'A' > f && cat <<B > g\nrm 1\nA\nrm 2\nB\nnode x", 'cat <<EOF > f\nno terminator\nrm x', 'cat <<<word\nrm x\nword',
    "$s = @'\nrm -rf x\n'@\nnode a.js", '$s = @"\nrm x\n"@ | Out-File f', "@'\nx\n'@ | python -", "@'\nx\n  '@ ; rm y",
    'powershell -Command "Get-Process | Sort CPU"', 'pwsh -c "rm -r x; node a"', 'bash -c "cd x && npm test"',
    'bash -c "bash -c \'bash -c \\"node x\\"\'"', "powershell -c 'cat a'", 'powershell -NoProfile -File run.ps1',
    'powershell -Command', 'cmd /c dir', 'cmd /C build.bat', 'sh x.sh', 'bash ./run.sh arg', 'pwsh -c ""',
    'X=$(ls -1 | head -1) && echo $X', 'X=$((1+2)) node a.js', 'f=$(cat a.json)', '$p = (Get-ChildItem .)',
    '$x = "C:/a"; node b', "$x = 'lit'", '$x = $null', '$x += Get-Content f', '$x', 'try { node a.js } catch {}',
    'try{ rm x }', 'q() { cat a; }; q', 'function f { rm x }', 'if [ -f a ]; then node b; fi', 'for i in 1 2; do rm $i; done',
    'while true; do sleep 1; done', 'time npm run build', 'env A=1 node x', 'nohup node a & disown', 'sudo rm -rf /tmp/x',
    '! grep -q x f', '( cd a && make )', '{ ls; }', 'git', 'git -C', 'git -C a -c b=c status', 'git --git-dir=.git log',
    'git --work-tree w diff', 'git log -G foo', 'git log --oneline -S', 'git stash pop', 'git stash list', 'git STASH list',
    'git Log', 'git worktree add x', 'git clean -fd', 'git rm a', 'git fetch && git status', 'git frobnicate',
    'gh', 'gh -R a/b', 'gh api /x -X POST', 'gh api /x --method patch', 'gh api -f a=b /x', 'gh api /x -F a=b',
    'gh api /x --field=a', 'gh api -X GET /x', 'gh search code x', 'gh release create v1', 'gh pr view 1',
    'gh pr checks', 'gh issue comment 3', 'gh repo clone a/b', 'gh pr', 'npm publish', 'npm PUBLISH', 'npm run x',
    'npx tsc -b', 'node.EXE a.js', 'C:/x/node.cmd a', 'python3 a.py', 'python3.12 a.py', 'python3.x a.py', 'Python3 a',
    'py -3 a.py', 'foo.bat.cmd.exe', 'x.exe.cmd', '"C:/Program Files/nodejs/node.exe" a.js', '"C:/tools/run.sh"',
    "'C:/x/y.ps1' -a b", './configure', '../bin/tool --x', 'C:\\x\\tool.exe /y', 'tool.sh', 'deploy.PS1',
    'echo hi > out.txt', 'echo hi >> out.txt', 'echo hi 2> err.txt', 'echo hi 2>&1', 'cat a >&2', 'cat a > b',
    'cat a 2>/dev/null', 'printf x | tee f', 'Write-Host hi', 'Write-Output x > f', 'date; pwd', 'which node; node -v',
    'sed -i.bak s/a/b/ f', 'sed --in-place s/a/b/ f', 'sed -E -n 1p f', 'sed -e s/a/b/ -i f', 'sed -n -e x -e y -i f',
    'diff -u a b', 'fc a b', 'Compare-Object $a $b', 'cmp a b', 'comp a b', 'robocopy a b /E', 'tar -czf a.tgz d',
    'Remove-Item -Recurse x', 'del /q x', 'Get-ChildItem -Recurse', 'gci', 'Test-Path a', 'New-Item -ItemType File a',
    'Set-Content a b', 'Out-File x', 'touch a', 'Start-Process node', 'Start-Sleep 5', 'Stop-Process -Id 1',
    'taskkill /F /PID 1', 'pkill node', 'Invoke-WebRequest u', 'iwr u', 'irm u', 'wget u', 'vercel deploy',
    'Get-Process node | Stop-Process', 'tasklist | findstr node', 'df -h', 'du -sh x', 'ping 1.1.1.1', 'ipconfig',
    'Get-NetTCPConnection -LocalPort 3000', 'netstat -ano | findstr 3000', 'systeminfo', 'Get-Counter x',
    'sha256sum a', 'pdftotext a.pdf -', 'hexdump -C x', 'Get-FileHash a', 'jq . a.json', 'awk 1 f', 'wc -l f',
    'sort f | uniq -c', 'tr a b < f', 'xxd f', 'od -c f', 'stat f', 'file f', 'more f', 'type f', 'gc f',
    'mv a b', 'Move-Item a b', 'ren a b', 'mkdir -p x', 'md x', 'cp -r a b', 'Copy-Item a b', 'xcopy a b', 'zip -r a d',
    'Expand-Archive a.zip', 'curl -s u | jq .', 'curl u -o f && unzip f', 'sleep 2 && curl u', 'kill 123; ls',
    'ls && ls && rm x', 'cat a; cat b; cp a b', 'npm test || echo failed', 'node a.js | tee log.txt',
    'echo "a|b" | node x', "echo 'a&&b' && cat f", 'echo a\\;b; node x', 'cat f\\', '\\ls', '`ls`', 'ls `pwd`',
    '$(node a.js)', '(node a.js)', '@(1,2) | % { rm $_ }', '[IO.File]::ReadAllText("a")', '"x" -f 1', "'x'",
    '"C:/a b/c d.py"', '"a" | node x', '& node a.js', '& "C:/x/y.exe" z', '. ./env.sh', 'source x.sh && node a',
    'export A=1; node a', 'set -e; rm x', 'local x=1', 'read x', 'exit 1', 'return', ': noop', 'true && node a',
    'cd /x\nnode a.js', 'cd /x\n\nls', '\n\n', 'ls ;', '; ls', 'ls &&', '&& ls', 'ls | | node', 'ls ||| node',
    'ls &&& node', 'ls & node', 'ls|&node', 'a=1 b=2', 'A=1', 'X="a b" Y=\'c d\' node x', 'X="a\nb" node x',
    'echo "line1\nline2" && rm f', "python -c 'print(1)\nprint(2)'", 'node -e "a;b;c"', 'Get-Content a\u2003| node b',
    '\u00e9cho a', 'ca\u0301t f', 'r\u00e9m x', 'git c\u00f6mmit', '\u0130ls', 'cat \u017fx', 'ls\u2009-la',
    'python\u0663 a', 'X\u0660=1 node a', 'q\u00e9() { rm x; }; q', 'f_\u0663() { rm x; }', '$\u00e9 = Get-Content a',
    'echo \u0661>&\u0662 x', 'node a \u0662> err.txt', 'node a \u0662>err.txt > out', 'echo x \u0662>f',
    # heredoc / here-string bodies that WOULD win if they were treated as commands (the self-test's own heredoc
    # case cannot tell: its body 'rm -rf build' ranks below the 'cat >' step either way)
    "cat > f.sh <<'EOF'\nnode build.js\nEOF", 'cat <<EOF > run.sh\nnpm test\nEOF', 'cat <<-X >a\n\tpython b.py\n\tX\nls',
    "$code = @'\nnode server.js\n'@\nSet-Content a.js $code", '$t = @"\ncurl https://x\n"@; $t | Out-File f',
    # Python's '.' matches \r,  ,   (only \n is excluded): quoted assignment values / literals holding them
    'X="a\rb" node x', 'X="a b" node x', 'X=\'p q\' node x', '$x = "a\rb" node', "$x = 'p q' cat f",
    # Python's strip() removes \x1c-\x1f and \x85 but not the BOM ﻿ (JS trim() is the opposite)
    'cat <<EOF > f\nrm x\nEOF\x85\nnode y', 'cat <<EOF > f\nrm x\n﻿EOF\nnode y', "@'\nx\n\x1c'@ ; node y",
    'python3.٣ a.py',
    # Unicode 16.0 additions that Python 3.13 (Unicode 15.1) does not know: a digit (python3.N, an fd before >) and a
    # letter (a function name). The port must answer as the reference does, whatever its JS engine's Unicode version.
    'python3.\U0001CCF1 a.py', 'echo done \U0001CCF2> err.log', 'gꟋ() { rm -rf x; }; g',
    'echo a \U00010D40>&\U00010D41 b > f', 'x\U00016130() { node a; }; x',
]
fx['edge'] = [shell_case(c) for c in E]

# ---- nest: P4, the segment-nesting bound (recipes; cmd = pre * k + mid + post * k)
N = cf.MAX_SEGMENT_NEST
NEST = []
def nest(pre, mid, post, ks):
    for k in ks:
        cmd = pre * k + mid + post * k
        NEST.append({'pre': pre, 'mid': mid, 'post': post, 'k': k, 'py': out(cf.classify_shell(cmd))})
around = [0, 1, N - 3, N - 2, N - 1, N, N + 1, N + 2]
nest('$a = ', 'rm x', '', around + [1200, 2000])                 # `$x = <command>` (R5): k levels = k + 1 open calls
nest('$a += ', 'Get-Content f', '', around)
nest('A=$(', 'ls', ')', around + [1200])                          # X=$( ... ) (R5), one token per level
nest('a=$( ', 'rm x', '', around + [2000])                        # X=$( with spaces: k tokens re-joined per level
nest('X=(', 'node a.js', '', around)                              # X=( ... (R5)
nest('bash -c "', '$a = rm x', '"', [0, 1])                       # R2 inside R5-free text
nest('', 'bash -c "' + '$a = ' * (N - 3) + 'rm x"', '', [0])      # R2 opens a level too: 1 + 1 + (N - 3) = N - 1
nest('', 'bash -c "' + '$a = ' * (N - 2) + 'rm x"', '', [0])      # = N open calls: still classified
nest('', 'bash -c "' + '$a = ' * (N - 1) + 'rm x"', '', [0])      # one more would open: no move
nest('', 'ls; ' + '$a = ' * N + 'rm x', '', [0])                 # the other step still counts
nest('', '$a = ' * N + 'rm x | node b', '', [0])                 # an unclassified first stage ends the pipeline
nest('', 'X=$( ' + '$a = ' * (N - 2) + 'curl u)', '', [0])       # mixed R5 branches: 1 + 1 + (N - 2) = N open
nest('', 'X=$( ' + '$a = ' * (N - 1) + 'curl u)', '', [0])       # one more would open: no move
nest('', 'X=$($a = curl u)', '', [0])                             # (lstrip('$(') also eats the $ of $a: no move)
fx['nest'] = NEST
assert any(c['py'][1] is None for c in NEST) and any(c['py'][1] is not None and c['k'] == N - 1 for c in NEST)

# ---- batchStations: every fixture batch and every one-call batch, at every station kind (reference classify_batch)
STATIONS = [None] + cf.PRECEDENCE + sorted(c3.LIBRARY_KINDS - set(cf.PRECEDENCE))
BS = [b['args'][0] for b in fx['batch'] if b['args'][0]]           # the batch cases' call lists (results unused)
TS = ['ToolSearch', {'query': 'q'}, 't']
for calls in ([TS], [TS, ['Read', {}, 'r']], [['Read', {}, 'r'], TS], [TS, ['Skill', {}, 's']], [['Skill', {}, 's'], TS],
              [TS, ['Foo', {}, 'f']], [['Foo', {}, 'f'], TS], [TS, ['Bash', {'command': 'git log -3'}, 'g']],
              [TS, ['Bash', {'command': 'npm test'}, 'n']], [['WebSearch', {}, 'w'], TS], [TS, ['WebFetch', {}, 'w']],
              [TS, ['Bash', {'command': 'cd x'}, 'c']], [['Bash', {'command': 'cd x'}, 'c'], TS], [TS, TS],
              [TS, ['Skill', {}, 's'], ['Read', {}, 'r']], [['Agent', {'run_in_background': True}, 'a'], TS],
              [['Agent', {'run_in_background': False}, 'a'], TS], [TS, ['SendMessage', {}, 'm']], [TS, ['ListAgents', {}, 'l']]):
    BS.append(calls)
for t in fx['tools']:                                             # every tool branch as a one-call batch
    name, inp, cur, res = t['args']
    if res == '' and cur is None: BS.append([[name, inp, 'x']])
_seen = set(); BS = [c for c in BS if not (json.dumps(c) in _seen or _seen.add(json.dumps(c)))]
fx['batchStations'] = {'stations': STATIONS, 'cases': [
    {'calls': calls, 'py': [out(cf.classify_batch([tuple(x) for x in calls], st)) for st in STATIONS]} for calls in BS]}

# ---- unicode: Python's \d and \w over every code point, as inclusive [first, last] ranges
def ranges(rx):
    r = re.compile(rx); res = []; start = prev = None
    for cp in range(0x110000):
        if r.fullmatch(chr(cp)):
            if start is None: start = cp
            prev = cp
        elif start is not None:
            res.append([start, prev]); start = None
    if start is not None: res.append([start, prev])
    return res
fx['unicode'] = {'d': ranges(r'\d'), 'w': ranges(r'\w')}

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps(fx, ensure_ascii=True, indent=1) + '\n', encoding='utf-8', newline='\n')
n = {k: len(v) for k, v in fx.items() if isinstance(v, list)}
print('wrote', OUT, n)
